### DISCUSSION TITLE
Change Powerstate in Automation (Siemens Coffee Maker)

### DISCUSSION THREAD

**Discussion by alando22** [ekutner/home-connect-hass#198] [General]
hi there,

I use a Seimens Coffee maker and the intergration works perfect. But I'm too stupid to call the right service to power on the coffe machine. The entity I copied from the (working) dashboard select is: **select.712010385904001148_bsh_common_setting_powerstate**
but I'm not able to turn the machine on within an automation. What would be the right service to change the power state?

**Comment by d0np3p3** [comment]
Hello,
Maybe the Powerstate musst be Change to fit the hm Logic, so IT IS, or can ve used as a Switch with in and Off, even the dryer cloud not be switch one.
My dryer and my Coffee Maschine settings are in the attached screenshots.

![Screenshot_20231215-085453.png](https://github.com/ekutner/home-connect-hass/assets/93970411/49b3e701-34db-4162-953a-8a4580e734ff)

![Screenshot_20231215-085418.png](https://github.com/ekutner/home-connect-hass/assets/93970411/de75b891-dcfb-4e20-8bd1-d834092ec7b8)

**Comment by nireins** [comment]
Hi here is my solution for this:

first: create a helper switch and give them a name. In my case "switch: Siemens_Kaffeemaschine"

Create a new automation:

```
alias: "Switch: Kaffeemaschine"
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.siemens_kaffeemaschine
    from: "off"
    to: "on"
    id: turn_on
  - platform: state
    entity_id:
      - input_boolean.siemens_kaffeemaschine
    from: "on"
    to: "off"
    id: turn_off
  - platform: state
    entity_id:
      - select.siemens_ti9575x1de_68a40e256c81_bsh_common_setting_powerstate
    to: BSH.Common.EnumType.PowerState.Standby
    id: Auto-Power-Off
  - platform: state
    entity_id:
      - select.siemens_ti9575x1de_68a40e256c81_bsh_common_setting_powerstate
    to: BSH.Common.EnumType.PowerState.On
    id: Power ON
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: turn_on
        sequence:
          - service: select.select_option
            data:
              option: BSH.Common.EnumType.PowerState.On
            target:
              entity_id:
                - >-
                  select.siemens_ti9575x1de_68a40e256c81_bsh_common_setting_powerstate
      - conditions:
          - condition: trigger
            id: turn_off
        sequence:
          - service: select.select_option
            data:
              option: BSH.Common.EnumType.PowerState.Standby
            target:
              entity_id: >-
                select.siemens_ti9575x1de_68a40e256c81_bsh_common_setting_powerstate
      - conditions:
          - condition: trigger
            id: Auto-Power-Off
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.siemens_kaffeemaschine
      - conditions:
          - condition: trigger
            id: Power ON
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.siemens_kaffeemaschine
mode: single
```
