### DISCUSSION TITLE
Rate limit question

### DISCUSSION THREAD

**Discussion by bkbartk** [ekutner/home-connect-hass#221] [General]
Hello. 

Yesterday I hit the rate limit. And it took until just now before my devices were available again.

my question is. Is it known what the rate limit is? And if so. Would it be possible to do a count and pause all requests when the limit is almost hit? This way you have a  minor downtime instead of 24hours.

**Comment by bkbartk** [comment]
for Now, I did the following,
installed "Spook" Useing hacs (read the readme)
created an input_datetime helper
and created the following automations.

```
- id: '1688496333777'
  alias: Home Connect Blocked disable
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.home_connect_status
    to: BLOCKED
  condition: []
  action:
  - service: homeassistant.disable_config_entry
    data:
      config_entry_id: a232350eca3de91cac21d835c7872c3e
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.home_connect_blocked
    data:
      timestamp: '{{ now().timestamp() }}'
  mode: single
- id: '1688496789225'
  alias: Home Connect Blocked Enable
  description: ''
  trigger:
  - platform: template
    value_template: '{{as_timestamp(now()) >= as_timestamp(states(''input_datetime.home_connect_blocked''))
      + (86400) }}'
  condition:
  - condition: state
    entity_id: sensor.home_connect_status
    state: BLOCKED
  action:
  - service: homeassistant.enable_config_entry
    data:
      config_entry_id: a232350eca3de91cac21d835c7872c3e
  mode: single
```
This should disable the integration as soon as it gets blocked and enable it 1 day later.
