### DISCUSSION TITLE
Bosch Washer-Dryer Remote Start problem - reported to Bosch but is it true for everyone?

### DISCUSSION THREAD

**Discussion by ando2040** [ekutner/home-connect-hass#321] [Community Support]
Hi, great integration. I installed it in the hope that it will help me get to the bottom of a problem but unfortunately the API is more restricted than the Home Connect App has access to. However it does allow me to graphically show the issue and ask if anyone else has it!

According to the manual, and Bosch themselves, Remote Start should stay active for 24 hours unless:
- Start/pause pressed
- Appliance switched off or power lost (even if power restored)
- door opened (both safety regulations - child or animal could have got inside)
 
Unfortunately, when the program reaches 100%, Remote Start disengages. This is not supposed to happen but I can prove it does:
![image](https://github.com/ekutner/home-connect-hass/assets/153862115/740221b8-175c-4905-bf0e-078e16f483c9)
Note that I accidentally left the door open the night before and never got around to going back to the machine - at least it proves the chart works and remote start stays on!

My use case is an overnight wash in Silent - 800 spin (sadly, Silent is only a sensor in the integration/API, I can't set it here).
I then want to start a 1400 spin when I wake up.
I don't want to visit the machine - I shouldn't have to because remote start is enabled!

So, please could some people with a washer press remote start, run a wash - it doesn't need to be started remotely - and run this chart (you will need to substitute your sensor names obviously) to prove that remote start works properly on their washer or is the same as mine? Ideally add the model in the chart title (mine is wdu8h541gb) and post a screenshot? Thanks!

```
type: custom:apexcharts-card
header:
  show: true
  title: Bosch Serie8 Washer-Dryer (wdu8h541gb)
  show_states: true
  colorize_states: true
series:
  - entity: binary_sensor.bosch_wdu8h541gb_xxxxxxx_bsh_common_status_doorstate
    transform: 'return x === "on" ? 100 : 0;'
    name: DoorState
    type: area
    color: red
    opacity: 0.2
    stroke_width: 0
    curve: stepline
    show:
      legend_value: false
      in_header: false
      name_in_header: false
      datalabels: false
  - entity: >-
      binary_sensor.bosch_wdu8h541gb_yyyyyyy_bsh_common_status_remotecontrolstartallowed
    transform: 'return x === "on" ? 100 : 0;'
    name: RemoteControlStartAllowed
    type: area
    color: grey
    opacity: 0.2
    stroke_width: 0
    curve: stepline
    show:
      legend_value: false
      in_header: false
      name_in_header: false
      datalabels: false
  - entity: sensor.bosch_wdu8h541gb_zzzzzzzzz_bsh_common_option_programprogress
    name: ProgramProgress
    type: area
    color: blue
    opacity: 0.2
    stroke_width: 0
    curve: stepline
    show:
      legend_value: false
      in_header: false
      name_in_header: false
      datalabels: false
yaxis:
  - min: 0
    max: 100
    show: false
```

EDIT: if you haven't got ApexCharts-Card, you won't regret installing it: https://github.com/RomRider/apexcharts-card

I will send any screenshots I receive to Bosch, as they've known about this for a month now but haven't given me an update.
