### DISCUSSION TITLE
Siemens Washer-Dryer Missing programs

### DISCUSSION THREAD

**Discussion by Plermpel** [ekutner/home-connect-hass#428] [Community Support]
Hi,

I just got into home assistant and I know the FAQ says it's normal that some features are missing in the API, but still I wanted to ask, if there is any way to get the missing programs from a device into home assistant?
There are every programs for Washing in the integration but for some reason for washing and drying there are only three. Sadly the one programm I usually used is not availiable and it's also not possible to pre select the programm on the machine and then start it through home assistant,  because than it says "Selected Program: Unknown". Is there any Way arround this, I just want my washer to automaticly start, when there is enough solar power.

**Comment by ekutner** [comment]
The available programs are determined by the API, so if it's not there then it's not made available.
That said, it may be possible to start the program currently selected on the appliance without it being explicitly supported by the API. I didn't try it myself so I'm not sure but it's worth a try:
* Make sure the appliance is configured to allow remote start
* Use the start_program service 
* Set ```validate: false```
* DON'T pass the program_key parameter.

**Reply by Plermpel** [reply]
Sadly that doesn't work, I get an error that the program_key is required.

Strangely they list the missing program keys in their documentation, but if I try to execute:

```
action: home_connect_alt.start_program
data:
  validate: true
  device_id: xyxyxyxyxyxyxyxyxxxyxxyxxy
  program_key: LaundryCare.WasherDryer.Program.Cotton
  options:
    - key: LaundryCare.Washer.Option.Temperature
      value: LaundryCare.Washer.EnumType.Temperature.GC30
    - key: LaundryCare.Washer.Option.SpinSpeed
      value: LaundryCare.Washer.EnumType.SpinSpeed.RPM1400
    - key: LaundryCare.Dryer.Option.DryingTarget
      value: LaundryCare.Dryer.EnumType.DryingTarget.CupboardDryPlus
```


I get the error:

The specified program in not one of the available programs (not supported by the API)
