### DISCUSSION TITLE
message when finished

### DISCUSSION THREAD

**Discussion by Thorsten1982** [ekutner/home-connect-hass#473] [Community Support]
Hello, how do you send a notification when a device is ready.

I tried it like that but it doesn't work

alias: Waschmaschine fertig
description: ""
triggers:
  - entity_id:
      - sensor.484010392717000356_bsh_common_status_operationstate
    trigger: state
    to: Finished
conditions:
  - condition: time
    after: "07:00:00"
    before: "19:00:00"
actions:
  - action: tts.google_translate_say
    data:
      cache: false
      entity_id: media_player.uberall_mas_2
      message: Waschmaschine ist fertig
      language: de
mode: single

**Comment by MSL-DA** [comment]
```
triggers:
  - trigger: state
    entity_id:
      - sensor.bosch_015070545380008176_bsh_common_status_operationstate
    to: BSH.Common.EnumType.OperationState.Ready
    from: BSH.Common.EnumType.OperationState.Finished
```
