### DISCUSSION TITLE
Program Finished trigger

### DISCUSSION THREAD

**Discussion by alexeiw123** [ekutner/home-connect-hass#94] [Community Support] [answered]
Hi, Thanks for this integration. I've been using the included integration for a while and have been struggling to get completion automations working consistently across both the washer and dryer. Very excited to get this one working and see more reliable entities to use.

I see in the readme:
"Program Started" and "Program Finished" events are exposed as triggers for easier building of automation scripts.

Where do I see these and how do I use them in automations? I set an event listener for `home_connect_alt_event` for a whole washing cycle and got the below when the cycle started, but no event when the cycle finished?

I can built a state trigger from Run to Ready but it seems like that may trigger under other conditions.

I know this is a basic question, appreciate your help.

```
event_type: home_connect_alt_event
data:
  device_id: <cut>
  key: BSH.Common.Status.OperationState
  value: BSH.Common.EnumType.OperationState.Run
origin: LOCAL
time_fired: "2022-08-13T23:20:29.602495+00:00"
context:
  id: <cut>
  parent_id: null
  user_id: null
```
