### ISSUE TITLE
Support API server for China

### ISSUE THREAD

**Issue by joelliang** [ekutner/home-connect-hass#102]
In the Home Connect API documentation at https://api-docs.home-connect.com/general#introduction
It said:

> ### API of physical home appliances
> api.home-connect.com or
> 
> api.home-connect.cn - This domain has to be used if you want to create an application for China. In this case please enable Sync to China in the [account settings](https://developer.home-connect.com/user/me/edit#Account_Settings) to copy all clients to China.
> 

But currently, there is no settings for me to change the API_HOST to the CN server.
I could login and use the plugin without any issue if I change the API_HOST from "https://api.home-connect.com" to "https://api.home-connect.cn" in the `custom_components/home_connect_alt/const.py`

It's better we could add an configuration like this:
    api_host (optional - default = "https://api.home-connect.com")
or
    api_host (optional - default = "global") - Supported values: "global", "cn"

## Version of the custom_component
0.5.6

## Configuration

```yaml
home_connect_alt:
  client_id: '<my client id>'
  client_secret: '<my client secret'
  name_template: $appliance - $name
  language: 'zh-CN'
```

## Debug log

There is no error if I change the API_HOST from "https://api.home-connect.com" to "https://api.home-connect.cn" in the `custom_components/home_connect_alt/const.py`
