### ISSUE TITLE
Continuously blocked

### ISSUE THREAD

**Issue by jasperweiss** [ekutner/home-connect-hass#127]
## Describe the bug

Home connect service keeps getting blocked seconds after becoming unblocked. I have 3 appliances connected and show a lot of their states on my dashboard but it is my understanding that those are pushed from the API as they change rather than being fetched continuously so it shouldn't affect the rate limit. I have 1 automation that schedules the dishwasher but the blocking does not occur around the automation's configured time so I doubt that it is the culprit. 

## Version of the custom_component

0.5.7

## Configuration

```yaml

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
  
recorder:
  db_url: !secret mariadb
  purge_keep_days: 30
  commit_interval: 30
  
influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb_host
  port: 8086
  token: !secret influxdb_token
  organization: !secret influx_org
  bucket: homeassistant
  tags:
    source: HomeAssistant
  tags_attributes:
    - friendly_name
  default_measurement: units
  ignore_attributes:
    - icon

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes

panel_iframe:
  zigbee2mqtt:
    title: "Zigbee2MQTT"
    url: "http://10.0.0.1:8124"
    require_admin: true
    icon: mdi:zigbee
  influxdb:
    title: "InfluxDB"
    url: "http://10.0.0.1:8086"
    require_admin: true
    icon: mdi:chart-line
  wireguard:
    title: "Wireguard"
    url: "http://10.0.0.1:51829"
    icon: mdi:key-chain
    require_admin: true

monitor_docker:
  - name: Docker
    containers:
      - unifi-controller
      - homeassistant
      - zigbee2mqtt
      - wgui
      - mqtt
      - restic-server
      - adguard
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - state
      - status
      - memory
      - 1cpu_percentage
      
logger:
  default: warn
  logs:
    home_connect_async: debug
    home_connect_alt: debug
    custom_components.home_connect_alt: debug

home_connect_alt:
  client_id: !secret home_connect_client_id 
  client_secret: !secret home_connect_client_secret

template:
  - sensor: !include_dir_merge_list templates/sensors/
```

## Debug log

See [gist](https://gist.github.com/jasperweiss/f61c8b58453ea1a55fbf984665893c07)
