### ISSUE TITLE
Many 'does not generate unique IDs' at startup.

### ISSUE THREAD

**Issue by mark007** [ekutner/home-connect-hass#163]
## Describe the bug
When my HA instance starts, I get 6 errors from the home_connect_alt integration, all relating to the fact that it does not generate unique ids. Is this normal or would it require a fix?

## Version of the custom_component
Latest as of today.

## Configuration

```yaml

I simply have my client id and secret keys.

home_connect_alt:
  client_id: xxx
  client_secret: xxx

```

## Debug log

```text
Platform home_connect_alt does not generate unique IDs. ID homeconnect_status already exists - ignoring sensor.home_connect_status
Platform home_connect_alt does not generate unique IDs. ID xxx_programs is already used by select.xxx_programs - ignoring home_connect.xxx_programs
```
