### ISSUE TITLE
EnumType in history

### ISSUE THREAD

**Issue by jake404** [ekutner/home-connect-hass#18]
## Version of the custom_component
v0.4.5

## Configuration

```yaml

home_connect_alt:
  client_id: !secret homeconnectid
  client_secret: !secret homeconnectsecret

```

## Describe the bug
When looking at the history of for example, Operation State, it shows the EnumTypes.
![image](https://user-images.githubusercontent.com/12189899/170026266-387a3c83-bb9a-4d1b-874c-3ba02a82d0be.png)

## Debug log

```text

Nothing in the log

```
