### ISSUE TITLE
Extra Service  change_setting

### ISSUE THREAD

**Issue by Rep-Hueman** [ekutner/home-connect-hass#185]
Create a request for an extra service for adjusting various settings via scripts

```
change_setting:
  name: Changes a setting
  description: Changes a setting on device
  fields:
    device_id:
      description: The ID of the appliance to changes a setting on
      name: device_id
      required: true
      selector:
        device:
          integration: home_connect_alt
    key:
      name: Option key
      description: >
        The ENUM key of an option which is available for the current setting
      example: ConsumerProducts.CoffeeMaker.Setting.CupWarmer
      required: true
      selector:
        text:
    value:
      name: Option value
      description: >
        An allowed value for the specified option
      example: True
      required: true
      selector:
        text:
```

**Describe alternatives you've considered**

Just like this old integration has.
https://github.com/DavidMStraub/homeassistant-homeconnect
