### ISSUE TITLE
International character in the device name is incorrect

### ISSUE THREAD

**Issue by jake404** [ekutner/home-connect-hass#19]
## Version of the custom_component
v0.4.5

## Configuration

```yaml

home_connect_alt:
  client_id: !secret homeconnectid
  client_secret: !secret homeconnectsecret

```

## Describe the bug
After the component added one of my devices that has an international character is named wrong. TvĂ¤ttmaskin should be Tvättmaskin.
![image](https://user-images.githubusercontent.com/12189899/170040063-5dec0b3a-c7cf-49ee-a3ee-4ccf511ac313.png)

## Debug log

```text

Nothing in the log

```
