### ISSUE TITLE
HomeAssistant Home Connect Alt 

### ISSUE THREAD

**Issue by edegraaff** [ekutner/home-connect-hass#197]
## Describe the bug
I folowed the instructions and on my phone and pc i get this error:
error": "unauthorized_client",
  "error_description": "client not authorized for this oauth flow (grant_type)",

## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 4.4.180+
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4816
Installed Version | 1.31.0
Stage | running
Available Repositories | 1247
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 4
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8 maart 2023 om 16:17
-- | --
current_recorder_run | 25 maart 2023 om 20:44
estimated_db_size | 337.59 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

## Configuration

```yaml

# EdG 25-03-2023 https://github.com/ekutner/home-connect-hass
home_connect_alt:
  client_id: 756650C0786597C6F5D9458C746F9D2B95FE0secret
  client_secret: 7570395442A8ECAD18D09C4384F475A8Csecret

# https://www.home-assistant.io/integrations/my activation
my:.

```

## Debug log

```text
Paste the exception info here

```
