### ISSUE TITLE
Status : LOADING_FAILED

### ISSUE THREAD

**Issue by tagcashdev** [ekutner/home-connect-hass#215]
## Describe the [bug]
After adding home connect alt from HACS, then creating the Application on the home connect developer account, I added ls info in the configuration file as described in the instructions.
I then added a new home connect alt integration from "Device and services" connection to the home connect site back connection OK everything works fine until I restart my raspberry pi... after restart... status LOADING_FAILED .. .I waited several minutes .... hours .... day ... but despite some "INIT" status from time to time the status returns to LOADING_FAILED

I then added a new home connect alt integration then deleted the old one READY again but after a few hours back to LOADING_FAILED often after restarting home_assistant but it already happened without restarting...

Result : Entities of all appliance are unavailable :(

![entityState](https://user-images.githubusercontent.com/29637320/235960503-52541305-d6e1-454d-a3ef-c3d79e28ecec.png)
![ActualState](https://user-images.githubusercontent.com/29637320/235960507-cf566ce9-7588-48b8-97b7-0f77f20a34d3.png)
![historyStates](https://user-images.githubusercontent.com/29637320/235960511-66f2235a-9f4e-4c42-b609-cebadbe6fd5a.png)

## Version of the custom_component
0.6.1

## Configuration

```yaml

# Loads default set of integrations. Do not remove.
wake_on_lan:
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

device_tracker:
  ### BLUETOOTH LE ###
  - platform: bluetooth_le_tracker
    consider_home: 180
    interval_seconds: 60
    new_device_defaults:
      track_new_devices: true
  ### BLUETOOTH ###
  - platform: bluetooth_tracker
    consider_home: 180
    interval_seconds: 60
    new_device_defaults:
      track_new_devices: true

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
proximity: !include proximity.yaml

home_connect_alt:
  client_id: !secret home_connect_alt_client_id
  client_secret: !secret home_connect_alt_client_secret
  sensor_value_translation: server
  language: fr

```

## Debug log

```text
home_connect_async.common.HomeConnectError: ('Failed to get a valid response from Home Connect server', 902, None, None, None)
```
