### ISSUE TITLE
Error occurred loading flow for integration home_connect_alt: No module named 'marshmallow_enum'

### ISSUE THREAD

**Issue by Nurgus** [ekutner/home-connect-hass#219]
## Describe the bug
Upon upgrading Home Assistant to 2023.5.0 (via the official docker), Home Connect Alt failed to load. An error message appears in the logs: No module named 'marshmallow_enum'. Prior to this, Home Connect Alt had been working great with my 3 appliances for weeks.

## Version of the custom_component
0.6.1

## Configuration

```yaml

home_connect_alt:
  client_id: <>
  client_secret: <>
  sensor_value_translation: server
  language: en-GB


```

## Debug log

```text
2023-05-05 11:28:33.817 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration home_connect_alt: No module named 'marshmallow_enum'
```
