### ISSUE TITLE
Wrong encoding used for device names

### ISSUE THREAD

**Issue by envy** [ekutner/home-connect-hass#22]
## Version of the custom_component
0.4.5

## Configuration

```yaml
home_connect_alt:
  client_id: !secret homeconnect_client_id
  client_secret: !secret homeconnect_client_secret
  language: de

```

## Describe the bug
My dishwasher is named "Geschirrspüler" (German for dishwasher). The imported device is named "GeschirrspĆ¼ler". 

There seems to be a worng encoding used at some point. The Home Connect app shows the name correctly.
