### ISSUE TITLE
The device is disabled by Config entry.

### ISSUE THREAD

**Issue by davidepanato** [ekutner/home-connect-hass#225]
## Describe the bug
All entities are disabled, home assistant shows The device is disabled by Config entry.
<img width="677" alt="Screenshot 2023-05-16 alle 15 01 41" src="https://github.com/ekutner/home-connect-hass/assets/17148168/3b6d06de-438a-4bb6-a938-12ad0b1e28d8">

## Version of the custom_component
0.6.1

## Configuration

```yaml

home_connect_alt:
  client_id: !secret HC_CLIENT_ID
  client_secret: !secret HC_CLIENT_SECRET

```

## Debug log

[home-assistant_2023-05-16T12-55-23.382Z.log](https://github.com/ekutner/home-connect-hass/files/11488033/home-assistant_2023-05-16T12-55-23.382Z.log)
