### ISSUE TITLE
Several errors in the log

### ISSUE THREAD

**Issue by Krocko** [ekutner/home-connect-hass#3]
I see the following errors in the Home Assistant log:
[home-assistant (1).log.txt](https://github.com/ekutner/home-connect-hass/files/8052611/home-assistant.1.log.txt)

**Comment by Krocko** [comment]
Some more errors. 
[home-assistant (2).log.txt](https://github.com/ekutner/home-connect-hass/files/8053023/home-assistant.2.log.txt)

**Comment by ekutner** [comment]
It seems there there was some problem loading cached data which then cascaded into other issues.
Please remove the integration, then update to the latest version (make sure you get v0.2.6) then restart HA an then add the integration back again. This should give us a clean start.

It seems that you've already done this but please make sure you have logging enabled in your config:
```
logger:
  default: info
  logs:
    home_connect_async: debug
    home_connect_alt: debug
    custom_components.home_connect_alt: debug
```
If you still see issues then please upload the log again. Thank you and sorry for the back and forth, I keep discovering edge cases where the API is not behaving as documented and I have to add special handling.
