### ISSUE TITLE
Inability to select Favorite program

### ISSUE THREAD

**Issue by Alfy1080** [ekutner/home-connect-hass#311]
## Describe the bug
Hello. Not sure if this should be possible or not, but i am trying to call the Home Connect Alt: Select Program service from the HA dev tools in order to select the favourite smart cycle configured and stored via the app in my BSH dishwasher but i get an error.

## Version of the custom_component
1.0.1

## Debug log
[error_log-1.txt](https://github.com/ekutner/home-connect-hass/files/13854876/error_log-1.txt)

Failed to call service home_connect_alt.select_program. The selected program key is not available

This is the way I am trying to call the service:
```
service: home_connect_alt.select_program
data:
  validate: true
  device_id: 0b1d0e86f582523e658450126f04f0d8
  program_key: BSH.Common.Program.Favorite.001
```
However when I do so I get the error "Failed to call service home_connect_alt.select_program. The selected program key is not available".

If I press the Favorite button on the dishwasher I can see some of the entities are changing values like so:
```
sensor.403100517583003871_selected_program = BSH.Common.Program.Favorite.001 (I assumed this is the key that I should reference in the service call)
sensor.403100517583003871_bsh_common_option_programname = Smart Cycle Custom (the name that i've set in the app for the favorite program)
```
Is this supposed to work and I am doing something wrong? Please let me know. Thank you! :)
