### ISSUE TITLE
Broken in core 2024.2.2

### ISSUE THREAD

**Issue by timoverwoest** [ekutner/home-connect-hass#347]
Integration does not load anymore: 

Core 2024.2.2
Supervisor 2024.02.0
Operating System 11.5
Frontend 20240207.1

BR
Timo

**Comment by rudizl** [comment]
Remove everything:
```
home_connect_alt:
  client_id: 
  client_secret: 
  language: 
```
