### ISSUE TITLE
Cooking.Oven.Event.PreheatFinished

### ISSUE THREAD

**Issue by geoced** [ekutner/home-connect-hass#370]
**Is your feature request related to a problem? Please describe.**
The official HC API documentation says that this event (Cooking.Oven.Event.PreheatFinished) is triggered when program option FastPreheat is active and the preheating phase is finished. But I don't see it in the lists of possible triggers when I select my Siemens device.

**Describe the solution you'd like**
I'd like to be able to trigger an automation when fast preheat has finished.

**Describe alternatives you've considered**
I've tried an event trigger but it didn't work. I used to do this with IFTTT but I'd like to remove as many cloud dependencies as possible.

Oven model: Siemens HB578A0S6
HC alt v1.1.6

**Comment by ekutner** [comment]
If the event is indeed published by the API it will also be published to the HA event bus by the integration. You should listen for it with an automation or the developer tools.

**Comment by geoced** [comment]
Thanks ! I missed that information. I was able to trigger an automation with:
```yaml
trigger:
  - platform: event
    event_type: home_connect_alt_event
    event_data:
      key: Cooking.Oven.Event.PreheatFinished
```
