### ISSUE TITLE
Events are not sent.

### ISSUE THREAD

**Issue by dlgoodr** [ekutner/home-connect-hass#447]
On 1.1.11, Events matching [`*.event.*`](https://github.com/ekutner/home-connect-hass/blob/695c4f1c116ca36ae251b0ec9ba389d33256f592/custom_components/home_connect_alt/const.py#L72) are not actually sent in to home assistant. replacing L72 with simply `"*"` will result in events being sent. It is also overkill and not a long term solution.

For example, an automation trace after the local change:

```
this:
  entity_id: automation.refrigerator_event
  state: 'on'
  attributes:
    id: '1733229962005'
    last_triggered: '2024-12-05T02:33:33.400177+00:00'
    mode: parallel
    current: 0
    max: 10
    friendly_name: 'Refrigerator: Event'
  last_changed: '2024-12-05T01:58:47.403371+00:00'
  last_reported: '2024-12-05T02:33:33.400617+00:00'
  last_updated: '2024-12-05T02:33:33.400617+00:00'
  context:
    id: 01JEAAMQEQ8FKTSHTPYC2MTD9D
    parent_id: 01JEAAMQEQSAT4MJ30KCB1DB90
    user_id: null
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: event
  event:
    event_type: home_connect_alt_event
    data:
      device_id: f2edc3dead1a379beef22cecfaae4971
      key: Refrigeration.FridgeFreezer.Event.DoorAlarmRefrigerator
      value: BSH.Common.EnumType.EventPresentState.Present
    origin: LOCAL
    time_fired: '2024-12-05T02:35:33.423983+00:00'
    context:
      id: 01JEAARCNFBG73K79H7CKSN0E9
      parent_id: null
      user_id: null
  description: event 'home_connect_alt_event'
```

Based on the code I would have expected to see this with the code as-shipped, but the event does not make it in.
