### ISSUE TITLE
HA 2025.01.1 Integration 'home_connect_alt' does not support device automation triggers

### ISSUE THREAD

**Issue by DJBenson** [ekutner/home-connect-hass#468]
## Describe the bug
The latest version of Home Assistant has thrown the below error with my automations.

![image](https://github.com/user-attachments/assets/bb262360-85b8-4295-b1a7-6ad9d60e0c90)

## Version of the custom_component
1.1.12

## Configuration
None

## Debug log
Will upload from desktop

**Comment by ekutner** [comment]
Did it ever work?
Please attach the YAML of your autmation

**Comment by DJBenson** [comment]
Yes it worked. There are no triggers listed in the automation any more so it never triggers.

```
alias: Notify Washer or Dryer Started or Finished
description: ""
mode: single
triggers:
  - alias: Dryer Started
    device_id: ffec8c41587a4d1bea2d61c354921150
    domain: home_connect_alt
    type: program_started
    id: dryer_started
    trigger: device
  - device_id: ffec8c41587a4d1bea2d61c354921150
    domain: home_connect_alt
    type: program_finished
    id: dryer_finished
    alias: Dryer Finished
    trigger: device
  - device_id: 491ee957d3070c4fae1b80063417a2db
    domain: home_connect_alt
    type: program_started
    id: washer_started
    alias: Washer Started
    trigger: device
  - device_id: 491ee957d3070c4fae1b80063417a2db
    domain: home_connect_alt
    type: program_finished
    id: washer_finished
    alias: Washer Finished
    trigger: device
  - alias: Dryer Started
    device_id: ffec8c41587a4d1bea2d61c354921150
    domain: button
    entity_id: 6e0b8ba5118c2c66c51a02378ce3ad91
    type: pressed
    id: dryer_started
    trigger: device
conditions:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
actions:
  - data:
      message: >-
        {% set trigger = trigger.id %} {% set parts = trigger.split('_') %} {%
        set device = parts[0] %} {% set action = parts[1] %} The {{ device }}
        has {{ action }}.
    action: notify.mobile_app_myphone
    enabled: false
  - choose:
      - conditions:
          - condition: trigger
            id:
              - washer_started
              - dryer_started
        sequence:
          - data:
              message: The {{ trigger }} has started
            action: notify.mobile_app_myphone
      - conditions:
          - condition: trigger
            id:
              - dryer_finished
              - washer_finished
        sequence: []
    enabled: false
  - data_template:
      is_critical: false
      is_debug: false
      is_system: false
      message: >-
        {% set trigger = trigger.id %} {% set parts = trigger.split('_') %} {%
        set device = parts[0] %} {% set action = parts[1] %} The {{ device }}
        has {{ action }}.
    enabled: true
    action: script.notification_handler
```
