### ISSUE TITLE
After upgrading to version 0.5.1 "common setting powerstate" not available

### ISSUE THREAD

**Issue by rafkan20** [ekutner/home-connect-hass#68]
Hi.
After upgrading to
0.5.1 "select.011100517384019627_bsh_common_setting_powerstate" not available in the dishwasher.
My configuration:
```
home_connect_alt:
  client_id: !secret home_connect_alt_client_id
  client_secret: !secret home_connect_alt_client_secret
  language: pl
```
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
