### ISSUE TITLE
Finishinrelative time for washing machines and dryers

### ISSUE THREAD

**Issue by code-echobase** [ekutner/home-connect-hass#8]
Love this new integration for home_connect appliances.

I have a dryer and washing machine and due to the limitations of these appliances, options need to be specified when starting a program rather than selecting a program. The Select service allows options to be specified but the Start program service doesn't.

Example would be finishinrelative xxx seconds. API details https://api-docs.home-connect.com/programs-and-options?#washer_finish-in-relative-option

Perhaps start in relative should be a number rather than just a sensor, and the start program service references the finish in relative number?

My use case is I have a time of day electricity tariff and I tend to set start in relative using the other integration so these machines run at the cheapest electricity time.

**Comment by ekutner** [comment]
Thank you!
Usually the way is to set the selected program and its option then just start it. I wasn't even aware there are options that can only be set when starting a program.
I've added the option to set the program and options in the service. I didn't have time to test it so I hope it works. Let me know if it doesn't and I'll look into it. You can find it in v0.3.10

**Comment by code-echobase** [comment]
thanks - using the service call with this yaml:
```
service: home_connect_alt.start_program
data:
  program_key: LaundryCare.Dryer.Program.Cotton
  device_id: 37896287148d4ea10df51f1a66d62149
  options:
    - key: BSH.Common.Option.FinishInRelative
      value: '10000'
```
I get the error message:
2022-02-17 20:00:57 ERROR (MainThread) [home_connect_async.appliance] Either "program" or "key" must be specified

Also I think the finishinrelative api call needs a unit option (unit: seconds) as well as a value
https://api-docs.home-connect.com/programs-and-options?#washer_finish-in-relative-option
