### ISSUE TITLE
Remaining program time incorrectly displays as 2022 seconds instead of a timestamp

### ISSUE THREAD

**Issue by Motik68** [ekutner/home-connect-hass#80]
## Configuration

```yaml

home_connect_alt:
  client_id: ***************
  client_secret: *****************
  name_template: $brand $appliance - $name
  language: fr  
  # sensor_value_translation: <server | local>  

```

## Describe the bug
The bsh_common_option_remainingprogramtimes sensor contains a timestamp (for instance: 2022-07-04T20:54:49+00:00) but displays as a float always equal to 2022.0 seconds.

The reason seems to be that the sensor's attributes (as found in the HA database) erroneously contain a unit of measurement (in my case: {"unit_of_measurement":"seconds","device_class":"timestamp","icon":"mdi:office-building-cog","friendly_name":"Bosch Lave-vaisselle  - Dur\u00e9e restante "}).

Similar, but correctly working, sensors from other integrations do not have the "unit_of_measurement":"seconds" part.

## Debug log

![image](https://user-images.githubusercontent.com/22507182/178162484-cfdab22e-e76e-47ec-b7ad-92ca5e476171.png)
