### ISSUE TITLE
Installation instruction is difficult to understand

### ISSUE THREAD

**Issue by oywino** [ekutner/home-connect-hass#98]
## Describe the bug
I've downloaded and installed this integration from HACS (with no apparent issues)
Then I added the following to my _configuration.yaml_:
```
home_connect_alt:
  client_id: MyClientID
  client_secret: MyClientSecret
  name_template: $brand $appliance - $name
```

Replacing _MyClientID_ and _MyClientSecret_ with actual values.
The name_template line written just as shown.

Then I did the _Check Configuration_ and got _Configuation valid!_ as response, and I restarted HA.
No error in the log during start up.

But what should I expect to find? And where? I can't see anything anywhere indicating that something new has happened.
The original HA HomeConnect integrations runs as before and all entities appear unchanged.  I cant seem to find any trace of _home_connect_alt_ anywhere.

Please advise.

## Version of the custom_component
 0.5.5

## Configuration

```yaml

Add your configuration here.

home_connect_alt:
  client_id: MyClientID
  client_secret: MyClientSecret
  name_template: $brand $appliance - $name



## Debug log

<!-- 
Check the README for instuctions on how to enable debug logging

If the bug results in an exception paste it below, in all other cases please attach the entire log file
-->

```text
Add your logs here (or attach the log file).

```

**Comment by ekutner** [comment]
HACS installs the integration but did you actually add it to HA?

**Comment by oywino** [comment]
Good question.
I thought adding the following to my _configuration.yaml_ ;

```
home_connect_alt:
  client_id: MyClientID
  client_secret: MyClientSecret
  name_template: $brand $appliance - $name
```
....  was how to add it to HA (?)  Am I wrong?
